Gemspec/RequireMFA:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/DuplicateBranch:
  IgnoreLiteralBranches: true

Lint/MissingSuper:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Metrics/ClassLength:
  Max: 400

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 200

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/NumberedParametersLimit:
  Max: 2

Style/NumericLiterals:
  MinDigits: 7

Style/OptionalBooleanParameter:
  AllowedMethods:
    - "perform"

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Style/RedundantFetchBlock:
  SafeForConstants: true

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  Enabled: false
